### ISSUE TITLE
How do you batch visualize these motions？

### ISSUE THREAD

**Issue by mornfairy** [sigal-raab/MoDi#4]
Your demo video is cool, and batch visualization is good for viewing the results. Can you tell me how to visualize these motions? What software is used? How does this work?

**Comment by sigal-raab** [comment]
Hi @mornfairy, 
We used an adjustment of the code from https://github.com/DeepMotionEditing/deep-motion-editing#blender-visualization.
It uses the Blender Python packages.

**Comment by sigal-raab** [comment]
I am closing the issue. Feel free to reopen it if needed.
