### ISSUE TITLE
Pre-trained model link require permissions to access. 

### ISSUE THREAD

**Issue by WinstonHuTiger** [sigal-raab/MoDi#8]
Hi Sigal,

Really Appreciate the wonderful work you have open-sourced. When I want to test the model on my own dataset, I found the link for the pre-trained model requiring permission to access. I am wondering if it is possible that you can make it accessible. I would really appreciate that. Thank you so much for this.

**Comment by sigal-raab** [comment]
Hi @WinstonHuTiger,
We made a recent change and probably switched the link to a non-accessible one. Sorry for that.
Please try again and let me know if it is accessible now.
However, if your own dataset does not share the same topology and motion distribution as the one we used for training, then I am not sure you will be able to use the pre-trained model for it.
Anyway, we can guide you how to use MoDi for any dataset.

**Comment by WinstonHuTiger** [comment]
Hi @sigal-raab , 
I can access the link now. I am trying to use the pre-trained encoder on AMASS for motion fusion. 
Thank you very much for the update.
